package migrations

import "github.com/angvp/tango/migration"

// Migrations is every migration in this project, in application order.
// It is regenerated by `tango makemigrations` — do not hand-edit it.
var Migrations = []migration.Migration{
	{App: "blog", Name: "0001_initial", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "author", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "name", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}}},
			migration.CreateTable{Table: "draft", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "note", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "post", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "title", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "body", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "score", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "author_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false, References: "author"}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "comment", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "post_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false, References: "post"}, {Name: "text", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "comment"},
			migration.DropTable{Table: "post"},
			migration.DropTable{Table: "draft"},
			migration.DropTable{Table: "author"},
		},
	},
	{App: "blog", Name: "0002_add_fields", Reversible: true,
		Up: []migration.Step{
			migration.AddColumn{Table: "post", Column: migration.Column{Name: "published", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}},
			migration.AddColumn{Table: "post", Column: migration.Column{Name: "rating", Type: "real", PrimaryKey: false, Unique: false, Indexed: false}},
		},
		Down: []migration.Step{
			migration.DropColumn{Table: "post", Column: "rating"},
			migration.DropColumn{Table: "post", Column: "published"},
		},
	},
	{App: "blog", Name: "0003_constraints", Reversible: true,
		Up: []migration.Step{
			migration.AlterColumnUnique{Table: "author", Column: "name", Unique: false},
			migration.AlterColumnUnique{Table: "post", Column: "title", Unique: true},
			migration.CreateIndex{Table: "post", Column: "body"},
		},
		Down: []migration.Step{
			migration.DropIndex{Table: "post", Column: "body"},
			migration.AlterColumnUnique{Table: "post", Column: "title", Unique: false},
			migration.AlterColumnUnique{Table: "author", Column: "name", Unique: true},
		},
	},
	{App: "blog", Name: "0004_drop_index", Reversible: true,
		Up: []migration.Step{
			migration.DropIndex{Table: "post", Column: "body"},
		},
		Down: []migration.Step{
			migration.CreateIndex{Table: "post", Column: "body"},
		},
	},
	{App: "blog", Name: "0005_drop_field", Reversible: false,
		Up: []migration.Step{
			migration.DropColumn{Table: "post", Column: "published"},
		},
		Down: []migration.Step{},
	},
	{App: "blog", Name: "0006_drop_model", Reversible: false,
		Up: []migration.Step{
			migration.DropTable{Table: "draft"},
		},
		Down: []migration.Step{},
	},
	{App: "blog", Name: "0007_rename_field", Reversible: true,
		Up: []migration.Step{
			migration.RenameColumn{Table: "post", From: "title", To: "heading"},
		},
		Down: []migration.Step{
			migration.RenameColumn{Table: "post", From: "heading", To: "title"},
		},
	},
	{App: "blog", Name: "0008_rename_model", Reversible: true,
		Up: []migration.Step{
			migration.RenameTable{From: "author", To: "writer"},
		},
		Down: []migration.Step{
			migration.RenameTable{From: "writer", To: "author"},
		},
	},
	{App: "blog", Name: "0009_widen_type", Reversible: false,
		Up: []migration.Step{
			migration.AlterColumnType{Table: "post", Column: "score", From: "integer", To: "real"},
		},
		Down: []migration.Step{},
	},
}
