package migration

// Step is a typed, dialect-agnostic schema migration operation. It is exported
// so generated migration files and the tango CLI can share one representation;
// do not hand-author Step values directly in application code.
type Step interface {
	isMigrationStep()
}

// Column describes the SQL-relevant shape of one table column. It is exported
// for generated migration files and CLI diffing, not as a hand-authored v0.1
// application API.
type Column struct {
	Name       string
	Type       string
	PrimaryKey bool
	Unique     bool
	Indexed    bool
	// References is the target table name for a foreign key column (from a
	// tango:"fk=X" tag), or "" for an ordinary column. The generated
	// constraint is always RESTRICT/NO ACTION — see ADR 0010: cascade
	// delete is implemented by Store.Delete, never by the database itself.
	References string
	// Default is a raw SQL literal (e.g. "TRUE") the column is given as a
	// NOT NULL DEFAULT when adding it to an existing table, so pre-existing
	// rows backfill to that value instead of NULL. Empty means no default:
	// the column is added exactly as before this field existed. There is no
	// struct-tag-driven way to set this — it is only ever hand-authored on a
	// specific generated migration where an existing model needs it.
	Default string
}

// CreateTable creates a table with the provided columns. It is exported for
// generated migration files; application code should use the tango CLI.
type CreateTable struct {
	Table   string
	Columns []Column
}

// DropTable removes a table. It is exported for generated migration files;
// application code should use the tango CLI.
type DropTable struct {
	Table string
}

// AddColumn adds a column to an existing table. It is exported for generated
// migration files; application code should use the tango CLI.
type AddColumn struct {
	Table  string
	Column Column
}

// DropColumn removes a column from an existing table. It is exported for
// generated migration files; application code should use the tango CLI.
type DropColumn struct {
	Table  string
	Column string
}

// AlterColumnUnique changes a column's uniqueness constraint. It is exported
// for generated migration files; application code should use the tango CLI.
type AlterColumnUnique struct {
	Table  string
	Column string
	Unique bool
}

// CreateIndex creates a plain index for a table column. It is exported for
// generated migration files; application code should use the tango CLI.
type CreateIndex struct {
	Table  string
	Column string
}

// DropIndex removes a plain index for a table column. It is exported for
// generated migration files; application code should use the tango CLI.
type DropIndex struct {
	Table  string
	Column string
}

// Migration groups the up/down steps for one generated migration file. It is
// part of the runtime contract accepted by ApplyPending and RollbackLast, but
// application code should normally use values generated by tango makemigrations.
type Migration struct {
	App        string
	Name       string
	Up         []Step
	Down       []Step
	Reversible bool
}

func (CreateTable) isMigrationStep()       {}
func (DropTable) isMigrationStep()         {}
func (AddColumn) isMigrationStep()         {}
func (DropColumn) isMigrationStep()        {}
func (AlterColumnUnique) isMigrationStep() {}
func (CreateIndex) isMigrationStep()       {}
func (DropIndex) isMigrationStep()         {}
