package migration

// Step is a typed, dialect-agnostic schema migration operation. It is exported
// so generated migration files and the tango CLI can share one representation;
// do not hand-author Step values directly in application code.
type Step interface {
	isMigrationStep()
}

// Column describes the SQL-relevant shape of one table column. It is exported
// for generated migration files and CLI diffing, not as a hand-authored
// application API.
type Column struct {
	Name string
	Type string
	// Length is the maximum number of characters of a "varchar" column, and
	// 0 for every other type. It is an additive field: generated files
	// written before it existed leave it 0 and mean what they always meant.
	Length     int `json:",omitempty"`
	PrimaryKey bool
	Unique     bool
	Indexed    bool
	// References is the target table name for a foreign key column (from a
	// tango:"fk=X" tag), or "" for an ordinary column. The generated
	// constraint is always RESTRICT/NO ACTION: cascade delete is
	// implemented in application code by Store.Delete, never by the
	// database itself.
	References string
	// Default is a raw SQL literal (e.g. "TRUE") the column is given as a
	// NOT NULL DEFAULT when adding it to an existing table, so pre-existing
	// rows backfill to that value instead of NULL. Empty means no default:
	// the column is added exactly as before this field existed. There is no
	// struct-tag-driven way to set this — it is only ever hand-authored on a
	// specific generated migration where an existing model needs it.
	Default string
}

// CreateTable creates a table with the provided columns. It is exported for
// generated migration files; application code should use the tango CLI.
type CreateTable struct {
	Table   string
	Columns []Column
}

// DropTable removes a table. It is exported for generated migration files;
// application code should use the tango CLI.
type DropTable struct {
	Table string
}

// AddColumn adds a column to an existing table. It is exported for generated
// migration files; application code should use the tango CLI.
type AddColumn struct {
	Table  string
	Column Column
}

// DropColumn removes a column from an existing table. It is exported for
// generated migration files; application code should use the tango CLI.
type DropColumn struct {
	Table  string
	Column string
}

// AlterColumnUnique changes a column's uniqueness constraint. It is exported
// for generated migration files; application code should use the tango CLI.
type AlterColumnUnique struct {
	Table  string
	Column string
	Unique bool
}

// CreateIndex creates a plain index for a table column. It is exported for
// generated migration files; application code should use the tango CLI.
type CreateIndex struct {
	Table  string
	Column string
}

// DropIndex removes a plain index for a table column. It is exported for
// generated migration files; application code should use the tango CLI.
type DropIndex struct {
	Table  string
	Column string
}

// RenameColumn renames a column, keeping its data, constraints and indexes
// (an index named after the column takes the new name). It comes from a
// Rename mapping given to tango makemigrations. It is exported for
// generated migration files; application code should use the tango CLI.
type RenameColumn struct {
	Table string
	From  string
	To    string
}

// RenameTable renames a model's table, keeping its rows, constraints and
// indexes (an index named after the table takes the new name); other
// tables' foreign keys follow it. It comes from a Rename mapping given to
// tango makemigrations. It is exported for generated migration files;
// application code should use the tango CLI.
type RenameTable struct {
	From string
	To   string
}

// AlterColumnType changes a column's type by a Widening type change,
// converting every row's value with explicit SQL for the dialect. Default,
// when set, is the column's existing default converted to the new type (a
// raw SQL literal); the column keeps NOT NULL. A migration containing it
// is irreversible. It is exported for generated migration files;
// application code should use the tango CLI.
type AlterColumnType struct {
	Table  string
	Column string
	From   string
	// FromLength and ToLength are the varchar lengths of From and To, and 0
	// for any other type. They are additive: files written without them
	// mean what they always meant.
	FromLength int `json:",omitempty"`
	To         string
	ToLength   int `json:",omitempty"`
	Default    string
}

// Migration groups the up/down steps for one generated migration file. It is
// part of the runtime contract accepted by ApplyPending and RollbackLast, but
// application code should normally use values generated by tango makemigrations.
type Migration struct {
	App        string
	Name       string
	Up         []Step
	Down       []Step
	Reversible bool
}

func (CreateTable) isMigrationStep()       {}
func (DropTable) isMigrationStep()         {}
func (AddColumn) isMigrationStep()         {}
func (DropColumn) isMigrationStep()        {}
func (AlterColumnUnique) isMigrationStep() {}
func (CreateIndex) isMigrationStep()       {}
func (DropIndex) isMigrationStep()         {}
func (RenameColumn) isMigrationStep()      {}
func (AlterColumnType) isMigrationStep()   {}
func (RenameTable) isMigrationStep()       {}
