package migrations

import "github.com/angvp/tango/migration"

// tango:migration-json [{"app":"admin","name":"0001_auto_20261007040652","up":[{"kind":"CreateTable","table":"admin_session","columns":[{"Name":"id","Type":"integer","PrimaryKey":true,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"token","Type":"text","PrimaryKey":false,"Unique":true,"Indexed":false,"References":"","Default":""},{"Name":"user_id","Type":"integer","PrimaryKey":false,"Unique":false,"Indexed":true,"References":"","Default":""},{"Name":"expires_at","Type":"timestamp","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}],"def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"CreateTable","table":"admin_user","columns":[{"Name":"id","Type":"integer","PrimaryKey":true,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"username","Type":"text","PrimaryKey":false,"Unique":true,"Indexed":false,"References":"","Default":""},{"Name":"password_hash","Type":"text","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"active","Type":"boolean","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"is_staff","Type":"boolean","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"is_superuser","Type":"boolean","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"created_at","Type":"timestamp","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}],"def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}}],"down":[{"kind":"DropTable","table":"admin_session","def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"DropTable","table":"admin_user","def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}}],"reversible":true}]
var M0001Auto20261007040652 = []migration.Migration{
	{App: "admin", Name: "0001_auto_20261007040652", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "admin_session", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "token", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "user_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true}, {Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "admin_user", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "username", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "password_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "active", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "is_staff", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "is_superuser", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "admin_session"},
			migration.DropTable{Table: "admin_user"},
		},
	},
}
