package migrations

import "github.com/angvp/tango/migration"

// Migrations is every migration in this project, in application order.
// It is regenerated by `tango makemigrations` — do not hand-edit it.
var Migrations = []migration.Migration{
	{App: "admin", Name: "0001_auto_20261007040652", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "admin_session", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "token", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "user_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true}, {Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "admin_user", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "username", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "password_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "active", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "is_staff", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "is_superuser", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "admin_session"},
			migration.DropTable{Table: "admin_user"},
		},
	},
	{App: "posts", Name: "0002_auto_20261007040652", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "post", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "title", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "body", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "post"},
		},
	},
	{App: "posts", Name: "0003_auto_20261007040806", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "comment", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "post_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true, References: "post"}, {Name: "author", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "body", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "comment"},
		},
	},
	{App: "accounts", Name: "0004_auto_20261007040937", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "account", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "email", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "password_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "active", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "account_session", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "token", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "user_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true, References: "account"}, {Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "account"},
			migration.DropTable{Table: "account_session"},
		},
	},
	{App: "posts", Name: "0005_auto_20261007040937", Reversible: true,
		Up: []migration.Step{
			migration.AddColumn{Table: "post", Column: migration.Column{Name: "account_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true, References: "account"}},
		},
		Down: []migration.Step{
			migration.DropColumn{Table: "post", Column: "account_id"},
		},
	},
	{App: "accounts", Name: "0006_auto_20261008201421", Reversible: true,
		Up: []migration.Step{
			migration.AddColumn{Table: "account", Column: migration.Column{Name: "email_verified_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}},
			migration.CreateTable{Table: "account_token", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "token_hash", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "account_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true, References: "account"}, {Name: "purpose", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "address_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "account_token"},
			migration.DropColumn{Table: "account", Column: "email_verified_at"},
		},
	},
}
