// Package migrationtest builds a test's tables the way an app gets them:
// from the framework's own migrations, generated by migration.Diff and
// applied by migration.ApplyPending, in a database from testdb.Open.
//
// It is the one copy of that setup the framework's own suites share. It
// lives apart from testdb because testdb cannot import migration: the
// migration package's own tests import testdb.
package migrationtest

import (
	"context"
	"database/sql"
	"testing"

	"github.com/angvp/tango/db"
	"github.com/angvp/tango/migration"
	"github.com/angvp/tango/model"
)

// initialName is the name each app's generated migration gets, as
// `tango makemigrations` names an app's first migration.
const initialName = "0001_initial"

// Apply creates a table for each of models in sqlDB, a database from
// testdb.Open, by applying the migrations Diff generates for them from an
// empty schema. It fails the test if they do not apply.
func Apply(t testing.TB, sqlDB *sql.DB, dialect db.Dialect, models []model.ModelMeta) {
	t.Helper()
	migrations, err := migration.Diff(models, migration.SchemaState{})
	if err != nil {
		t.Fatalf("migrationtest: diff: %v", err)
	}
	named := make([]migration.Migration, len(migrations))
	for i, m := range migrations {
		m.Name = initialName
		named[i] = m
	}
	if err := migration.ApplyPending(context.Background(), sqlDB, dialect, named); err != nil {
		t.Fatalf("migrationtest: migrate: %v", err)
	}
}
