package migrations

import "github.com/angvp/tango/migration"

// Migrations is every migration in this project, in application order.
// It is regenerated by `tango makemigrations` — do not hand-edit it.
var Migrations = []migration.Migration{
	{App: "posts", Name: "0001_auto", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "post", Columns: []migration.Column{migration.Column{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, migration.Column{Name: "title", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "body", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "post"},
		},
	},
	{App: "authors", Name: "0002_auto", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "author", Columns: []migration.Column{migration.Column{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, migration.Column{Name: "name", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "email", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "author"},
		},
	},
}
