package migrations

import "github.com/angvp/tango/migration"

// Migrations is every migration in this project, in application order.
// It is regenerated by `tango makemigrations` — do not hand-edit it.
var Migrations = []migration.Migration{
	{App: "posts", Name: "0001_auto", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "post", Columns: []migration.Column{migration.Column{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, migration.Column{Name: "title", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "body", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "post"},
		},
	},
	{App: "authors", Name: "0002_auto", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "author", Columns: []migration.Column{migration.Column{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, migration.Column{Name: "name", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "email", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "author"},
		},
	},
	{App: "admin", Name: "0003_auto", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "admin_session", Columns: []migration.Column{migration.Column{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, migration.Column{Name: "token", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, migration.Column{Name: "user_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true}, migration.Column{Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "admin_user", Columns: []migration.Column{migration.Column{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, migration.Column{Name: "username", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, migration.Column{Name: "password_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "active", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, migration.Column{Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "admin_session"},
			migration.DropTable{Table: "admin_user"},
		},
	},
	{App: "posts", Name: "0004_auto", Reversible: true,
		Up: []migration.Step{
			migration.AddColumn{Table: "post", Column: migration.Column{Name: "author_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false, References: "author"}},
		},
		Down: []migration.Step{
			migration.DropColumn{Table: "post", Column: "author_id"},
		},
	},
}
