package migrations

import "github.com/angvp/tango/migration"

// tango:migration-json [{"app":"blog","name":"0001_initial","up":[{"kind":"CreateTable","table":"author","columns":[{"Name":"id","Type":"integer","PrimaryKey":true,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"name","Type":"text","PrimaryKey":false,"Unique":true,"Indexed":false,"References":"","Default":""}],"def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"CreateTable","table":"comment","columns":[{"Name":"id","Type":"integer","PrimaryKey":true,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"post_id","Type":"integer","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"post","Default":""},{"Name":"text","Type":"text","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}],"def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"CreateTable","table":"draft","columns":[{"Name":"id","Type":"integer","PrimaryKey":true,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"note","Type":"text","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}],"def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"CreateTable","table":"post","columns":[{"Name":"id","Type":"integer","PrimaryKey":true,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"title","Type":"text","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"body","Type":"text","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"score","Type":"integer","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""},{"Name":"author_id","Type":"integer","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"author","Default":""},{"Name":"created_at","Type":"timestamp","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}],"def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}}],"down":[{"kind":"DropTable","table":"author","def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"DropTable","table":"comment","def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"DropTable","table":"draft","def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}},{"kind":"DropTable","table":"post","def":{"Name":"","Type":"","PrimaryKey":false,"Unique":false,"Indexed":false,"References":"","Default":""}}],"reversible":true}]
var M0001Initial = []migration.Migration{
	{App: "blog", Name: "0001_initial", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "author", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "name", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}}},
			migration.CreateTable{Table: "comment", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "post_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false, References: "post"}, {Name: "text", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "draft", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "note", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "post", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "title", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "body", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "score", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "author_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: false, References: "author"}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "author"},
			migration.DropTable{Table: "comment"},
			migration.DropTable{Table: "draft"},
			migration.DropTable{Table: "post"},
		},
	},
}
