package migrations

import "github.com/angvp/tango/migration"

// Migrations is every migration in this project, in application order.
// It is regenerated by `tango makemigrations` — do not hand-edit it.
var Migrations = []migration.Migration{
	{App: "accounts", Name: "0001_initial", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "account", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "email", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "password_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "active", Type: "boolean", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "email_verified_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "account_session", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "token", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "user_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true, References: "account"}, {Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
			migration.CreateTable{Table: "account_token", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "token_hash", Type: "text", PrimaryKey: false, Unique: true, Indexed: false}, {Name: "account_id", Type: "integer", PrimaryKey: false, Unique: false, Indexed: true, References: "account"}, {Name: "purpose", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "address_hash", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "expires_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "account_token"},
			migration.DropTable{Table: "account_session"},
			migration.DropTable{Table: "account"},
		},
	},
	{App: "profiles", Name: "0002_initial", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "profile", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "account_id", Type: "integer", PrimaryKey: false, Unique: true, Indexed: false, References: "account"}, {Name: "username", Type: "varchar", Length: 30, PrimaryKey: false, Unique: true, Indexed: false}, {Name: "display_name", Type: "varchar", Length: 60, PrimaryKey: false, Unique: false, Indexed: false}, {Name: "bio", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "profile"},
		},
	},
}
