package migrations

import "github.com/angvp/tango/migration"

// Migrations is every migration in this project, in application order.
// It is regenerated by `tango makemigrations` — do not hand-edit it.
var Migrations = []migration.Migration{
	{App: "greetings", Name: "0001_auto", Reversible: true,
		Up: []migration.Step{
			migration.CreateTable{Table: "greeting", Columns: []migration.Column{{Name: "id", Type: "integer", PrimaryKey: true, Unique: false, Indexed: false}, {Name: "name", Type: "text", PrimaryKey: false, Unique: false, Indexed: false}, {Name: "created_at", Type: "timestamp", PrimaryKey: false, Unique: false, Indexed: false}}},
		},
		Down: []migration.Step{
			migration.DropTable{Table: "greeting"},
		},
	},
}
